---
title: "Untitled"
author: "kim soyeon"
date: "2023-09-05"
output: html_document
---

```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)
library(phyloseq)
library(vegan)
library(tibble)


ps <- readRDS("./ps.rds")
ps.rel <- phyloseq::transform_sample_counts(ps, fun = function(x) x/sum(x))
otu_table(ps.rel) %>% head
```


# Sample  and NMDS
```{r}
ps.cl <- tax_glom(ps.rel, taxrank = "Class")

otu <- otu_table(ps.cl) %>% t()
tax <- tax_table(ps.cl) %>% as.matrix()

dist <- phyloseq::distance(ps.cl, method = "bray", type = "species")

set.seed(42)
ord <- phyloseq::ordinate(physeq = ps.cl, method = "NMDS", distance = dist)
NMDS = data.frame(NMDS1 = ord$points[,1], NMDS2 = ord$points[,2])
NMDS.2 <- merge(NMDS, as.data.frame(tax[, "Phylum"]), by = "row.names") 


env <- envfit(NMDS, t(otu), perm = 999)
vec<-as.data.frame(env$vectors$arrows)
vec.2 <- cbind(vec, `SampleID` =rownames(vec))



p <- ggplot(NMDS.2) +
  geom_point(mapping = aes(x = NMDS1, y = NMDS2, color =  Phylum), alpha = 0.7) + 
  coord_fixed() + 
  geom_segment(data = vec.2,
               aes(x = 0, xend = NMDS1, y = 0, yend = NMDS2),
               #arrow = arrow(length = unit(0.25, "cm")), 
               colour = "grey") +
  geom_text(data = vec.2, aes(x = NMDS1, y = NMDS2, label = SampleID),
            size = 3) + 
  theme_bw()
p

ggsave("./Envfit_example01.png", width = 10, height = 10)
```

# Phylum and NMDS
```{r}
ps.g <- ps.rel %>% tax_glom(taxrank = "Phylum")
otu <- otu_table(ps.g)
tax <- tax_table(ps.g) %>% as.matrix()
s.dist <- phyloseq::distance(ps.g, method = "unifrac", type = "Samples")

set.seed(42)
s.ord <- phyloseq::ordinate(physeq = ps.g, method = "NMDS", distance = s.dist)
s.NMDS = data.frame(NMDS1 = s.ord$points[,1], NMDS2 = s.ord$points[,2])

s.NMDS.2 <- merge(s.NMDS, sample_data(ps.g)[, "body.site"],  by = "row.names")%>% 
  column_to_rownames("Row.names")
s.env <- envfit(s.NMDS, t(otu), perm = 999)
s.env



ordiplot (s.ord, display = 'sites')
plot (s.env)


s.vec<-as.data.frame(s.env$vectors$arrows)
s.vec$p.val <-  s.env$vectors$pvals
s.vec2 <- s.vec[s.vec$p.val < 0.05, ]

s.vec3 <- merge(s.vec2, tax[, "Phylum"], by = "row.names") %>% 
  column_to_rownames("Row.names")


 
p <- ggplot(s.NMDS.2) +
  geom_point(mapping = aes(x = NMDS1, y = NMDS2, color =  body.site), alpha = 0.7) + 
  coord_fixed() + ## need aspect ratio of 1!
  geom_segment(data = s.vec3,
               aes(x = 0, xend = NMDS1, y = 0, yend = NMDS2),
               arrow = arrow(length = unit(0.25, "cm")), colour = "grey") +
  geom_text(data = s.vec3, aes(x = NMDS1, y = NMDS2, label = Phylum), size = 3, check_overlap=TRUE) + 
  theme_bw()
p

ggsave("./Envfit_example02.png", width = 10, height = 10)
```
# Example
- https://www.davidzeleny.net/anadat-r/doku.php/en:suppl_vars_examples
```{r}
vltava.spe <- read.delim ('https://raw.githubusercontent.com/zdealveindy/anadat-r/master/data/vltava-spe.txt', row.names = 1) # [97 × 274]
vltava.env <- read.delim ('https://raw.githubusercontent.com/zdealveindy/anadat-r/master/data/vltava-env.txt') # 97 × 28

PCA <- rda (X = decostand (log1p (vltava.spe), method = 'hellinger'))


ef <- envfit (PCA ~ ASPSSW + SOILDPT + pH, data = vltava.env, perm = 999)
ef
ef.adj <- ef 
pvals.adj <- p.adjust (ef$vectors$pvals, method = 'bonferroni')
ef.adj$vectors$pvals <- pvals.adj
ef.adj

ordiplot (PCA, display = 'sites')
plot (ef)

scores.pca <- scores (PCA, display = 'sites', choices = 1:2)
scores.pca


cor (vltava.env [, c('ASPSSW', 'SOILDPT', 'pH')], scores.pca)

arrow_heads <- ef$vectors$arrows  # extracts matrix of coordinates of arrow heads from ef
r2 <- ef$vectors$r                # extracts vector of r2 for each env. variable
arrow_heads * sqrt (r2)



ordisurf (PCA, vltava.env[, 'pH'], main = 'pH + SOILDPT')
ordisurf (PCA, vltava.env[, 'SOILDPT'], add = T, col = 'green')
legend ('topleft', col = c('red', 'green'), lty = 1, legend = c('pH', 'SOILDPT'))

```


```{r}
ps.g <- ps.rel %>% tax_glom(taxrank = "Phylum")
otu <- otu_table(ps.g) 
tax <- tax_table(ps.g) %>% as.matrix()
sample.dist <- phyloseq::distance(ps.g, method = "bray", type = "Samples")



library(ade4)
# PCoA
obs.pcoa=dudi.pco(cailliez(sample.dist), scannf=F, nf=2)
s.class(obs.pcoa$li, fac=as.factor(sample_data(ps.g)$body.site), grid=F, col = c("#0073C2FF","#EFC000FF", "green", "red"))


ps.g <- ps.rel %>% tax_glom(taxrank = "Phylum")
otu <- otu_table(ps.g) %>% as.matrix()
tax <- tax_table(ps.g) %>% as.matrix()
s.dist <- phyloseq::distance(ps.g, method = "wunifrac", type = "Samples")


groups <- sample_data(ps.g)[, "body.site"]
pcoa <- cmdscale(s.dist)
efit <- envfit(pcoa, t(otu_table(ps.g)))

ef.adj <- efit 
pvals.adj <- p.adjust (efit$vectors$pvals, method = 'bonferroni')
ef.adj$vectors$pvals <- pvals.adj
ef.adj


ef.arr<-as.data.frame(ef.adj$vectors$arrows*sqrt(ef.adj$vectors$r))

s.vec <- ef.arr
s.vec$p.val <-  ef.adj$vectors$pvals
s.vec.2 <- s.vec[s.vec$p.val < 0.05, ]
s.vec.3 <- merge(s.vec.2, tax[, "Phylum"], by = "row.names") %>% column_to_rownames("Row.names")



pcoa.2 <- cbind(pcoa, groups)



p <- ggplot(pcoa.2) +
  geom_point(aes(x=`1`, y=`2`, color =  body.site), alpha = 0.7) + 
  coord_fixed() + 
  geom_segment(data = s.vec.3,
               aes(x = 0, xend = Dim1, y = 0, yend = Dim2),
               arrow = arrow(length = unit(0.25, "cm")), colour = "grey") +
  geom_text(data = s.vec.3, aes(x = Dim1, y = Dim2, label = Phylum), size = 3, check_overlap=TRUE) + 
  theme_bw()
p

ggsave("./Envfit_example03.png", width = 10, height = 10)


```


```{r}
ps.gn <- ps.rel %>% tax_glom(taxrank = "Genus") %>% 
  subset_samples(body.site %in% c("gut", "tongue"))
otu <- otu_table(ps.gn) %>% as.matrix()
tax <- tax_table(ps.gn) %>% as.matrix()

# 거리 구하기 
s.dist <- phyloseq::distance(ps.gn, method = "wunifrac", type = "Samples")


groups <- sample_data(ps.gn)[, "body.site"]
PCoA <- phyloseq::ordinate(physeq = ps.gn, method = "PCoA", distance = s.dist)
pcoa <- PCoA$vectors[, 1:2]
envfit <- envfit(pcoa, t(otu_table(ps.gn)))


ef.arr<-as.data.frame(envfit$vectors$arrows*sqrt(envfit$vectors$r))

s.vec <- ef.arr
s.vec$p.val <-  envfit$vectors$pvals
s.vec.2 <- s.vec[s.vec$p.val < 0.05, ]
s.vec.3 <- merge(s.vec.2, tax[, "Genus"], by = "row.names") %>% column_to_rownames("Row.names")



pcoa.2 <- cbind(pcoa, groups)

p <- ggplot(pcoa.2) +
  geom_point(aes(x=`Axis.1`, y=`Axis.2`, color =  body.site), alpha = 0.7) + 
  coord_fixed() + 
  geom_segment(data = s.vec.3,
               aes(x = 0, xend = Axis.1, y = 0, yend = Axis.2),
               arrow = arrow(length = unit(0.25, "cm")), colour = "grey") +
  geom_text(data = s.vec.3, aes(x = Axis.1, y = Axis.2, label = Genus), size = 3, check_overlap=TRUE) + 
  theme_bw()
p

ggsave("./Envfit_example04.png", width = 10, height = 10)


```

