---
title: "Untitled"
author: "kim soyeon"
date: "2023-10-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


https://www.microbiomestat.wiki/setting-up-microbiomestat-installation-and-data-preparation/kick-start-your-journey-the-microbiomestat-installation-guide
```{r }
library(phyloseq)
library(tidyverse)
library(devtools)
```


```{r}
devtools::install_github("cafferychen777/MicrobiomeStat")


# install.packages("MicrobiomeStat")
# 
# packages_to_install <- c(
#   "rlang",
#   "tibble",
#   "ggplot2",
#   "matrixStats",
#   "lmerTest",
#   "foreach",
#   "modeest",
#   "dplyr",
#   "pheatmap",
#   "tidyr",
#   "ggh4x",
#   "GUniFrac",
#   "stringr",
#   "rmarkdown",
#   "knitr",
#   "pander",
#   "tinytex",
#   "vegan",
#   "scales",
#    "ape",
#   "ggrepel",       # Used only in the linda.plot function
#   "parallel",      # Utilized only when setting parallel in linda
#   "ggprism",       # Active only when theme.choice is set to “prism”
#   "aplot",         # Operates exclusively in generate_beta_ordination_single
#   "philentropy",   # Used when dist.name is set to "JS"
#   "forcats",       # Comes into play only within barplot and areaplot
#   "yaml",          # Employed solely in mStat_import_qiime2_as_data_obj
#   "biomformat",    # Used in mStat_import_biom_as_data_obj
#   "Biostrings"     # Required for mStat_import_qiime2_as_data_obj and mStat_import_dada2_as_data_obj
# )
# 
# # Installing packages
# install.packages(packages_to_install)

```

## import phyloseq to mStat
```{r}
# Required package
library(microbiome)
library(MicrobiomeStat)
# Load the dataset
data(peerj32)


ps <- readRDS("./ps.rds")

peerj32.phy <- peerj32$phyloseq

# Convert the Phyloseq object to a MicrobiomeStat data object
# data.obj <- mStat_convert_phyloseq_to_data_obj(peerj32.phy)
# 
# 
# 
# data.obj$meta.dat$sex <- factor(as.factor(data.obj$meta.dat$sex), levels = c("male", "female"))
# 
# head(data.obj$meta.dat)
# head(data.obj$feature.tab)
# head(data.obj$feature.ann)

ps <- readRDS("./ps.rds")

data.obj <- mStat_convert_phyloseq_to_data_obj(ps)


# ## alpha 
# alpha <- generate_alpha_test_single(
#   data.obj = data.obj,
#   alpha.obj = NULL, 
#   alpha.name = c("shannon", "observed_species"),
#   depth = NULL,
#   time.var = "time",
#   t.level = "2",
#   group.var = "group",
#   adj.vars = "sex")
# alpha
# 
# alpha.p <- generate_alpha_boxplot_single(
#   data.obj = data.obj,
#   alpha.obj = NULL,
#   alpha.name = c("shannon"),
#   depth = NULL,
#   subject.var = "subject",
#   time.var = NULL,
#   t.level = NULL,
#   group.var = "group",
#   strata.var = NULL,
#   base.size = 16,
#   theme.choice = "bw",
#   palette = NULL,
#   pdf = TRUE,
#   file.ann = NULL,
#   pdf.wid = 11,
#   pdf.hei = 8.5)
# 
# alpha.p
# 
# alpha.p2 <- generate_alpha_boxplot_single(
#   data.obj = data.obj,
#   alpha.obj = NULL,
#   alpha.name = c("shannon"),
#   depth = NULL,
#   subject.var = "subject",
#   time.var = "time",
#   t.level = "2",
#   group.var = "group",
#   strata.var = "sex",
#   base.size = 16,
#   theme.choice = "bw",
#   palette = NULL,
#   pdf = TRUE,
#   file.ann = NULL,
#   pdf.wid = 11,
#   pdf.hei = 8.5)
# alpha.p2
# 

## beta 
beta.df <- generate_beta_test_single(
  data.obj = data.obj,
  dist.obj = NULL,
  t.level = "2",
  group.var = "body.site", 
  dist.name = c('BC', 'Jaccard') 
)
beta.df$p.tab
beta.df$aov.tab



library(aplot)
# generate_beta_ordination_single(
#   data.obj = data.obj,
#   dist.obj = NULL,
#   pc.obj = NULL,
#   subject.var = "subject",
#   time.var = "time",
#   t.level = "2",
#   group.var = "group",
#   strata.var = "sex",
#   adj.vars = "sex",
#   dist.name = c("BC"),
#   base.size = 20,
#   theme.choice = "bw",
#   custom.theme = NULL,
#   palette = NULL,
#   pdf = TRUE,
#   file.ann = NULL,
#   pdf.wid = 11,
#   pdf.hei = 8.5
# )
# 
# p <- generate_beta_ordination_single(
#   data.obj = peerj32.obj,
#   dist.obj = NULL,
#   pc.obj = NULL,
#   subject.var = "subject",
#   time.var = "time",
#   t.level = "2",
#   group.var = "group",
#   strata.var = "sex",
#   adj.vars = "sex",
#   dist.name = c("BC"),
#   base.size = 20,
#   theme.choice = "bw",
#   custom.theme = NULL,
#   palette = NULL,
#   pdf = TRUE,
#   file.ann = NULL,
#   pdf.wid = 11,
#   pdf.hei = 8.5
# )
# 
# # Add a p-value annotation to the plot. The p-value is calculated from a PERMANOVA test.
# p <- p + annotate("text", x = 0.3, y = 0.8, 
#   label = paste("italic(p) == ", 
#   format(pvalue, digits = 2)), 
#   parse = TRUE, 
#   size = 5)
# 
# p
data.obj$meta.dat$subject
data.obj$meta.dat$SubjectID <- rownames(data.obj$meta.dat)
p <- generate_beta_ordination_single(
  data.obj = data.obj,
  dist.obj = NULL,
  pc.obj = NULL,
  subject.var = "SubjectID",
  group.var = "body.site",
   strata.var = "subject",
  dist.name = c("BC"),
  base.size = 10,
  theme.choice = "bw",
  custom.theme = NULL,
  palette = NULL,
  pdf = TRUE,
  file.ann = NULL,
  pdf.wid = 11,
  pdf.hei = 8.5,
  
)

p
?generate_beta_ordination_single
```




## Beta 
```{r}
library(vegan)
library(glue)
library(ggtext)
# library(ggplotify)
library(ggpubr)
library(patchwork)
library(phyloseq)
library(tidyverse)

ps <- readRDS("./ps.rds")
ps.rel  <- phyloseq::transform_sample_counts(ps, function(x) x/sum(x))
meta <- sample_data(ps.rel)
meta$SampleID <- rownames(meta)
sample_data(ps.rel) <- meta

## 
phyloseq = ps.rel
index = "bray"
seed = 42
type = "body.site"
plot = "PCoA"
SampleID = "SampleID"
shap = NULL
type_col = col4 = c("#E31A1C", "#1F78B4", "#4D4D4D", "green")
## 
set.seed(seed)
x.dist <- phyloseq::distance(phyloseq, method = index)

myfunc <- function(v1) {
deparse(substitute(v1))
}
dist <- myfunc(x.dist)
a <- adonis2(as.formula (glue("{dist} ~ {type}")), data=data.frame(sample_data(phyloseq)),
             permutations=9999, method=index)
Perm.p <- a$`Pr(>F)`[1]
# 
# set.seed(seed)
ord <- ordinate(phyloseq, plot, index)


# 
mat <- ord$vectors[, 1:2] %>% as.data.frame() %>%
  mutate(SampleID = rownames(.)) %>%
  arrange(SampleID)

meta <- sample_data(phyloseq) %>% data.frame() %>%
  arrange(SampleID)

pcoa_df <- inner_join(meta, mat, by = "SampleID")

# PCoA 1 and PCoA 2 
PC1 <- round(ord$values["Relative_eig"][1,]*100, 1)
PC2 <- round(ord$values["Relative_eig"][2,]*100, 1)



theme0 <- function(...) theme(
  legend.position = "none",
  panel.background = element_blank(),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  panel.margin = unit(0, "null"),
  axis.ticks = element_blank(),
  axis.text.x = element_blank(),
  axis.text.y = element_blank(),
  axis.title.x = element_blank(),
  axis.title.y = element_blank(),
  axis.ticks.length = unit(0, "null"),
  axis.ticks.margin = unit(0, "null"),
  panel.border = element_rect(color = NA), ...
)

##
col_position = "in"
main.plot <- pcoa_df %>% 
  ggplot2::ggplot(aes(x = Axis.1, y=Axis.2)) + 
  ggplot2::geom_vline(xintercept = 0, colour = "grey80") + 
  ggplot2::geom_hline(yintercept = 0, colour = "grey80") + 
  ggplot2::geom_point(aes_string(shape = shap, color=type),alpha = 0.7, size=2.5) +
  lims(x = c(-0.8, 0.8), y = c(-0.8, 0.8)) + 
  ggplot2::stat_ellipse(aes_string(color= type) ) + 
  ggplot2::theme_test() +
  ggplot2::scale_color_manual(values = type_col) +
  ggplot2::labs(
    y =paste0("PCoA2 (", PC2, "%)"),
    x =paste0("PCoA1 (", PC1, "%)")) +
  ggplot2::theme(plot.caption = element_text(hjust = 0)) +
  ggplot2::theme(plot.caption = element_markdown(), 
                 # aspect.ratio=1,
                 legend.position = "bottom", 
                 legend.title = element_blank())+
   theme(legend.position="none",plot.margin=unit(c(0,0,0,0),"points"))+
  theme(plot.margin=unit(c(0,0,0,0),"points"))+
  ggtext::geom_richtext(label.color = NA, size = 4, fill = NA,
                        # hjust = 0, vjust =0, x = -Inf, y = -Inf, # 왼쪽 아래
                        hjust = 0, vjust =1, x = -Inf, y = Inf, # 왼쪽 위 ㅇㅇ
                        label= paste0( "**", Title,"** ",  "<br>",
                                       "*p*-value=", Perm.p ) # "PERMANOVA",
                        )+
  if (col_position == "in") {
    theme(legend.position = c(0.9, 0.9 ),
          legend.justification = c("right", "top"),
          legend.box.just = "right")  
  } else{
    theme() 
      }
main.plot

## 
pcoa1.boxplot <-
  ggplot2::ggplot(pcoa_df) +
  ggplot2::geom_boxplot(ggplot2::aes(x = !!sym(type),y = Axis.1, fill = !!sym(type)), color = "black", alpha = 0.5, show.legend = F) +
  ggplot2::scale_fill_manual(values = type_col) +coord_flip() + 
  lims(y = c(-0.8, 0.8)) +  
  theme_void() 

pcoa1.boxplot



theme0 <- function(...) theme( legend.position = "none",
                               panel.background = element_blank(),
                               panel.grid.major = element_blank(),
                               panel.grid.minor = element_blank(),
                               panel.margin = unit(0,"null"),
                               axis.ticks = element_blank(),
                               axis.text.x = element_blank(),
                               axis.text.y = element_blank(),
                               axis.title.x = element_blank(),
                               axis.title.y = element_blank(),
                               axis.ticks.length = unit(0,"null"),
                               axis.ticks.margin = unit(0,"null"),
                               panel.border=element_rect(color=NA),...)

pcoa1.density <-
  ggplot(pcoa_df,aes(x=Axis.1 ,fill=!!sym(type))) + 
  geom_density(alpha=0.5) + 
  scale_x_continuous(breaks=NULL,expand=c(0.02,0)) +
  scale_y_continuous(breaks=NULL,expand=c(0.02,0)) +
  theme_bw() +
  lims(x = c(-0.8, 0.8)) +  
  theme0(plot.margin = unit(c(1,0,-0.48,2.2),"lines")) 
pcoa1.density

## 
pcoa2.boxplot <-
  ggplot2::ggplot(pcoa_df) +
  ggplot2::geom_boxplot(ggplot2::aes(x =  !!sym(type),y = Axis.2, fill = !!sym(type)), color = "black", alpha = 0.5, show.legend = F) +
  ggplot2::scale_fill_manual(values = type_col) +
  lims(y = c(-0.8, 0.8))  + 
   theme_void() 
pcoa2.boxplot


pcoa2.density <-
  ggplot(pcoa_df,aes(x=Axis.2 ,fill=!!sym(type))) + 
  geom_density(alpha=0.5) + 
  scale_x_continuous(breaks=NULL,expand=c(0.02,0)) +
  scale_y_continuous(breaks=NULL,expand=c(0.02,0)) +
  theme_bw() +
  lims(x = c(-0.8, 0.8)) +  
  theme0(plot.margin = unit(c(0,1,1.2,-0.48),"lines")) + 
  coord_flip()  
pcoa2.density

```


```{r}
## patchwork
pcoa1.boxplot + plot_spacer() + main.plot + pcoa2.boxplot + 
  plot_layout(ncol = 2, nrow = 2, widths = c(4, 0.5), heights = c(0.5, 4))

ggsave("./patchwork.png", device = png)


pcoa1.density + plot_spacer() + main.plot + pcoa2.density + 
  plot_layout(ncol = 2, nrow = 2, widths = c(4, 0.5), heights = c(0.5, 4))
ggsave("./density.png", device = png)

```
https://stackoverflow.com/questions/8545035/scatterplot-with-marginal-histograms-in-ggplot2

```{r}
library(ggExtra)
ggExtra::ggMarginal(main.plot, type="histogram")
ggsave("./patchwork2.png", device = png)


```

```{r}


empty <- ggplot()+geom_point(aes(1,1), colour="white")+
         theme(axis.ticks=element_blank(), 
               panel.background=element_blank(), 
               axis.text.x=element_blank(), axis.text.y=element_blank(),           
               axis.title.x=element_blank(), axis.title.y=element_blank())

p <- gridExtra::grid.arrange(pcoa1.boxplot, empty, main.plot, pcoa2.boxplot, ncol=2, nrow=2, widths=c(4, 1), heights=c(1, 4))
ggsave(plot = p, "./patchwork3.png", device = png)







```

```{r}
library(ggpubr)

ggscatterhist(
  pcoa_df, x = "Axis.1", y = "Axis.2",
  color = "body.site", # comment out this and last line to remove the split by species
  margin.plot = "histogram", # I'd suggest removing this line to get density plots
  margin.params = list(fill = "body.site", color = "black", size = 0.2)
)

ggsave("./patchwork4.png", device = png)


ggscatterhist(
  pcoa_df, x = "Axis.1", y = "Axis.2",
  color = "body.site", # comment out this and last line to remove the split by species
  margin.plot = "density", # I'd suggest removing this line to get density plots
  margin.params = list(fill = "body.site", color = "black", size = 0.2)
)

ggsave("./density4.png", device = png)

```


```{r}
library("cowplot")

# p = plot_grid(
#   pcoa1.boxplot
#   , NULL
#   , main.plot
#   , pcoa2.boxplot
#   , ncol = 2
#   , nrow = 2
#   , rel_heights = c(0.2, 1)
#   , rel_widths = c(1, 0.2)
# )
# p
# ggsave(plot = p, "./patchwork5.png", device = png)
# 
# plot_grid(
#   pcoa1.density
#   , NULL
#   , main.plot
#   , pcoa2.density
#   , ncol = 2
#   , nrow = 2
#   , rel_heights = c(0.2, 1)
#   , rel_widths = c(1, 0.2)
# )
# 
# ggsave("./density5.png", device = png)



# Add density curves to y and x axis
xdens <- 
  axis_canvas(main.plot, axis = "x") + 
  geom_density(data = pcoa_df, aes(x = Axis.1, fill = body.site, colour = body.site), alpha = 0.3)
ydens <-
  axis_canvas(main.plot, axis = "y", coord_flip = TRUE) + 
  geom_density(data = pcoa_df, aes(x = Axis.1, fill = body.site, colour = body.site), alpha = 0.3) +
  coord_flip()
main.plot %>%
  insert_xaxis_grob(xdens, grid::unit(1, "in"), position = "top") %>%
  insert_yaxis_grob(ydens, grid::unit(1, "in"), position = "right") %>%
  ggdraw()
ggsave("./density5.png", device = png)



xbox <- 
  axis_canvas(main.plot, axis = "x") + 
  geom_boxplot(data = pcoa_df, aes(x = Axis.1, fill = body.site, colour = body.site), alpha = 0.3)
ybox <-
  axis_canvas(main.plot, axis = "y", coord_flip = TRUE) + 
  geom_boxplot(data = pcoa_df, aes(x = Axis.1, fill = body.site, colour = body.site), alpha = 0.3) +
  coord_flip()
main.plot %>%
  insert_xaxis_grob(xbox, grid::unit(1, "in"), position = "top") %>%
  insert_yaxis_grob(ybox, grid::unit(1, "in"), position = "right") %>%
  ggdraw()
ggsave("./patchwork5.png", device = png)




```


```{r}

ggExtra::ggMarginal(
  main.plot,
  type =c('boxplot'),
  margins = 'both',
  size = 3.5,
  groupColour = F,
  groupFill = T
) 


ggsave(paste0("./patchwork6.png"), width = 5, height = 4,
        dpi = 500, device = png, type = "cairo",  bg = "transparent")

ggExtra::ggMarginal(
  main.plot,
  type =c('density'),
  margins = 'both',
  size = 3.5,
  groupColour = F,
  groupFill = T
) 
ggsave(paste0("./density6.png"), width = 5, height = 4,
        dpi = 500, device = png, type = "cairo",  bg = "transparent")
```


```{r}
library(pracma )

comp_ <- pcoa_df$body.site %>% unique() %>% as.vector()
comp_pair <- combn(comp_, 2)

combined_list <- lapply(1:ncol(comp_pair), function(i) comp_pair[, i])

ybox <- 
  ggplot(pcoa_df, aes(x = body.site, y = Axis.2)) + 
  geom_boxplot(aes(fill = body.site, colour = body.site), alpha = 0.3)+
  scale_fill_manual(values = type_col) + 
  scale_color_manual(values = type_col) + 
  lims(y =c(-0.9, 0.9)) +
  stat_compare_means(method = "wilcox.test", tip.length=0.02,
                     label = "p.signif",
                     comparisons = combined_list) + 
  theme_void() + 
  theme(legend.title = element_blank(),
        legend.position = 'none',
        strip.background = element_blank())
  


xbox <- 
  ggplot(pcoa_df, aes(x = body.site, y = Axis.1)) + 
  geom_boxplot(aes(fill = body.site, colour = body.site), alpha = 0.3)+
  scale_fill_manual(values = type_col) + 
  scale_color_manual(values = type_col) + 
  lims(y =c(-0.9, 0.9)) +
  stat_compare_means(method = "wilcox.test", tip.length=0.02,
                     label = "p.signif",
                     comparisons = combined_list) + 
  theme_void() + 
  theme(legend.title = element_blank(),
        legend.position = 'none',
        strip.background = element_blank())+
  coord_flip()
  

```


```{r}


type_col <-  c("#E31A1C",  "#1F78B4",  "#4D4D4D",  "pink2")  

col_position = "in"
main.plot <- pcoa_df %>% 
  ggplot2::ggplot(aes(x = Axis.1, y=Axis.2)) + 
  ggplot2::geom_vline(xintercept = 0, colour = "grey80") + 
  ggplot2::geom_hline(yintercept = 0, colour = "grey80") + 
  ggplot2::geom_point(aes_string(shape = shap, color=type),alpha = 0.7, size=2.5) +
  lims(x = c(-0.8, 0.8), y = c(-0.8, 0.8)) + 
  ggplot2::stat_ellipse(aes_string(color= type) ) + 
  ggplot2::theme_test() +
  ggplot2::scale_color_manual(values = type_col) +
  ggplot2::labs(
    y =paste0("PCoA2 (", PC2, "%)"),
    x =paste0("PCoA1 (", PC1, "%)")) +
  ggplot2::theme(plot.caption = element_text(hjust = 0)) +
  ggplot2::theme(plot.caption = element_markdown(), 
                 # aspect.ratio=1,
                 legend.position = "bottom", 
                 legend.title = element_blank())+
  theme(legend.position="none",plot.margin=unit(c(0,0,0,0),"points"))+ 
  theme(plot.margin=unit(c(0,0,0,0),"points"))+
  ggtext::geom_richtext(label.color = NA, size = 4, fill = NA,
                        # hjust = 0, vjust =0, x = -Inf, y = -Inf, # 왼쪽 아래
                        hjust = 0, vjust =1, x = -Inf, y = Inf, # 왼쪽 위 ㅇㅇ
                        label= paste0( "**", Title,"** ",  "<br>",
                                       "*p*-value=", Perm.p ) # "PERMANOVA",
                        )+
  if (col_position == "in") {
    theme(legend.position = c(0.98, 0.98 ),
          legend.justification = c("right", "top"),
          legend.box.just = "right")  
  } else{
    theme() 
      }
main.plot


pcoa <- main.plot %>%
  cowplot::insert_yaxis_grob(ybox, grid::unit(1, "in"), position = "right") %>%
  cowplot::insert_xaxis_grob(xbox, grid::unit(1, "in"), position = "top") %>%
  
  ggdraw()
pcoa
ggsave(paste0("./patchwork7.png"), width = 5, height = 5,
        dpi = 500, device = png, type = "cairo",  bg = "transparent")

```
